### ISSUE TITLE
Pre-Trained models for down-stream tasks?

### ISSUE THREAD

**Issue by TheShadow29** [zmykevin/UVLP#1]
Hi @zmykevin 

Thanks for open sourcing the code!

I was wondering if you have plans to share the pre-trained models for downstream tasks (vqa, nlvr2, refcoco+ and ve). It would be really helpful.

**Comment by zmykevin** [comment]
Hi,
thanks for your interest in our work. Unfortunately, I did not back up the fine-tuned model from the company's server and currently, I don't have access to them. Sorry that I could not provide these fine-tuned checkpoints at this moment.

**Comment by TheShadow29** [comment]
Thanks for your reply. I will close this issue then!
